### ISSUE TITLE
Sails won't lift

### ISSUE THREAD

**Issue by blindman2k** [artificialio/docker-sails#13]
Hi. I had a play with PM2 and decided your dock was a good way to package Sails.

When I run in daemon more or interactive mode it locks up at:
info: Starting app...

If I run bash interactively I get the same lockup when I execute any npm command. Could it be that and how to I resolve it? I can ping out to the internet so I know the network plus DNS is working.

Thanks in advance.
    A.

**Comment by Globegitter** [comment]
@blindman2k That is odd, which image exactly are you using?

**Comment by blindman2k** [comment]
@Globegitter I just grabbed the current default version. I didn't specify any version.

**Comment by Globegitter** [comment]
@blindman2k which OS are you running. And are you running it with `docker-compose`? Sometimes running

```
docker-compose stop
docker-compose rm --force -v
```

or `boot2docker restart` helps

```
#Set up aliases in your .bashrc, .zshrc or config.fish
alias docker.clean='docker rm $(docker ps --no-trunc -aq)'
#deletes all your downloaded images
alias docker.cleanimages='docker rmi $(docker images --filter dangling=true --quiet)'
#in your project root folder run
docker.clean
docker.cleanimages
```

can sometimes help as well.

And lastly try the `artificial/docker-sails:iojs-full-stable-pm2` that is what I am using and it works fine.

**Comment by blindman2k** [comment]
@Globegitter, sorry but I gave up and moved to Heroku.

**Comment by Globegitter** [comment]
Ah ok yeah that is understandable - sorry for the slow responses. Has been busy! Will close that for now but feel free to come back if you try again.
