### ISSUE TITLE
Improve minimal iojs image

### ISSUE THREAD

**Issue by Globegitter** [artificialio/docker-sails#4]
Make a minimal iojs image that installs iojs via nvm, has git installed (so npm packages can be installed via git) and that can compile libraries such as bcrypt.

Also I think we don't actually need `RUN mkdir /server` in the files, but haven't tested that yet.

@kriswill that might be something you could tackle? To get the ideal iojs docker image :)

**Comment by kriswill** [comment]
yessir, I'll take a crack at it.

**Comment by Globegitter** [comment]
Thank you :)
