### ISSUE TITLE
nvm-iojs-latest build fix

### ISSUE THREAD

**Issue by okket** [artificialio/docker-sails#7]
```RUN bash -c ". $HOME/.bashrc && npm -g i sails@0.11 grunt bower pm2"```

I guess this "hack" is also needed for the CMD line(s) or else npm will not be found.

**Comment by Globegitter** [comment]
@okket could you explain a bit further? Do you mean Windows with 'CMD lines(s)'?

**Comment by okket** [comment]
No, not Windows, this CMD: 

https://docs.docker.com/reference/builder/#cmd

**Comment by okket** [comment]
I guess we can discuss this further in my PR
